backend:
  name: github
  repo: uffdg/maru
  branch: main
  base_url: https://marufiorillo.com
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Content"
    files:
      - name: "posts"
        label: "Blog Posts"
        file: "src/data/posts.json"
        format: "raw"
        editor:
          preview: false
        fields:
          - name: "body"
            label: "posts.json"
            widget: "code"
            default_language: "json"
            output_code_only: true
      - name: "cases"
        label: "Case Studies"
        file: "src/data/cases.json"
        format: "raw"
        editor:
          preview: false
        fields:
          - name: "body"
            label: "cases.json"
            widget: "code"
            default_language: "json"
            output_code_only: true
